name: Latest Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
      - name: Install dependencies
        run: |
          go mod tidy
      - name: Compile server
        run: bash ./build.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            output/*
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: vaalacat/mc-gateway:latest
